// examples/minimal/mfe-lit/src/lifecycle.ts
// The federated surface of this MFE — exposed as "./lifecycle" via the kit's
// default expose map. Lit renders into its own shadow root, so its styles
// travel with the element (no CSS asset for kit to inject).
import { defineMFE } from "@mfkit/kit";

import { MfkitLitBadge, TAG } from "./badge";

// customElements.define throws on a second definition — a remount, or two
// instances, must not crash the MFE.
if (!customElements.get(TAG)) customElements.define(TAG, MfkitLitBadge);

export default defineMFE({
  mount(el, ctx) {
    if (ctx.signal.aborted) return;
    const badge = document.createElement(TAG) as MfkitLitBadge;
    badge.basePath = ctx.basePath;
    el.replaceChildren(badge);
  },
  unmount(el) {
    el.replaceChildren();
  },
});

// examples/minimal/mfe-hello/src/lifecycle.tsx
// The federated surface of this MFE — exposed as "./lifecycle" by the kit's
// default expose map. The shell only ever sees { mount, unmount }.
import { defineMFE } from "@mfkit/kit";
import { createRoot, type Root } from "react-dom/client";

import { Hello } from "./Hello";

export interface HelloProps {
  readonly greeting?: string | undefined;
}

// One React root per container — a host may mount several instances.
const roots = new WeakMap<HTMLElement, Root>();

export default defineMFE<HelloProps>({
  mount(el, ctx, props) {
    if (ctx.signal.aborted) return;
    const root = createRoot(el);
    roots.set(el, root);
    root.render(<Hello greeting={props?.greeting} basePath={ctx.basePath} />);
  },
  unmount(el) {
    roots.get(el)?.unmount();
    roots.delete(el);
  },
});
